FORMAT: 1A

# Orders API

Order is a simple API allowing restbucks owner to place orders.

## Orders Collection [/orders]

### Get All Orders [GET]
You may get all orders using this action.

+ Response 200 (application/json)

        [
            {
                "_id": "58f01dd46ca8801aa8ad1e1a",
                "location": "San Francisco",
                "status": "PREPARING",
                "message": "Your order has been placed",
                "__v": 1,
                "items": [
                            {
                                "size": "large",
                                "milk": "whole",
                                "name": "latte",
                                "qty": 1
                            }
                        ]
            }
        ]

### Place a New Order [POST] 

You may create your a new order using this action. It takes a JSON
object containing a order details.

+ Request (application/json)

        {
            "location": "San Francisco",
            "items": [
                        {
                            "qty": 1,
                            "name": "latte",
                            "milk": "whole",
                            "size": "large"
                        }
                    ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /orders/5912475bda0da131987626f4

    + Body

            {
                "__v": 0,
                "location": "San Francisco",
                "status": "PLACED",
                "message": "Your order has been placed",
                "_id": "5912475bda0da131987626f4",
                "items": [
                            {
                                "qty": 1,
                                "size": "large",
                                "milk": "whole",
                                "name": "latte"
                            }
                        ]
                "links":[
                            {
                                "get":"/orders/5912475bda0da131987626f4"
                                "pay":"/orders/5912475bda0da131987626f4/pay"
                                "delete":"/orders/5912475bda0da131987626f4"
                                "update":"/orders/5912475bda0da131987626f4"
                            }
                        ]
            }

+ Response 400 (application/json)

    + Body

            {
                "location": "San Francisco",
                "items": [
                            {
                                "qty": 1,
                                "name": "latte",
                                "milk": "whole",
                                "size": "large"
                            }
                        ]
            }
            

## Order [/orders/{order_id}]
+ Parameters
    + order_id (number) - ID of the Order in the form of an integer

### Get Order Details [GET] 

You may get your order detals using this action. It takes a Order ID as a parameter and
returns the order details.
    
+ Response 200 (application/json)

        
        {
            "_id": "58f01dd46ca8801aa8ad1e1a",
            "location": "San Francisco",
            "status": "PREPARING",
            "message": "Your order has been placed",
            "__v": 1,
            "items": [
                        {
                            "size": "large",
                            "milk": "whole",
                            "name": "latte",
                            "qty": 1
                        }
                    ]
        }

+ Response 404

### Update an Order [PUT] 

You may update your order using this action. It takes a JSON
object containing updated order details.

+ Request (application/json)

        {
            "location": "San Francisco",
            "items": [
                        {
                            "qty": 1,
                            "name": "latte",
                            "milk": "whole",
                            "size": "small"
                        }
                    ]
        }

+ Response 200 (application/json)

    + Body

            {
                "_id": "591249192dfef631a4405969",
                "location": "San Francisco",
                "status": "PREPARING",
                "message": "Your order has been updated",
                "__v": 1,
                "items": [
                            {
                                "size": "small",
                                "milk": "whole",
                                "name": "latte",
                                "qty": 1
                            }
                        ]
            }

+ Response 412

            
### Cancel an Order [DELETE] 

You may cancel your order using this action. It takes order ID as parameter.

+ Response 204 

+ Response 404



## Pay [/orders/{order_id}/pay] 

### Pay for an Order [POST] 

You may pay for your order using this action. It takes order ID as parameter.

+ Response 200 
    + Body

            {
                "_id": "591249192dfef631a4405969",
                "location": "San Francisco",
                "status": "PAID",
                "message": "Your payment has been accepted.",
                "__v": 1,
                "items": [
                            {
                                "size": "small",
                                "milk": "whole",
                                "name": "latte",
                                "qty": 1
                            }
                        ]
            }


+ Response 404

+ Response 412